// widget-iframe/v1/vite-vue/src/App.vue
<script setup>
import { ref } from 'vue'
import queryString from 'query-string'

const config = {
  // The address '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE' stands for the native token.
  fromTokenAddress: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
  sourceChainId: '1',
  toTokenAddress: '0x77777777772cf0455fB38eE0e75f38034dFa50DE',
  targetChainId: '1',
  amount: 1,
  slippage: '1',
  theme: 'dark',
  lockmode: 'none',
  referrer: '0x856ebdc948afFCc6E24FCe08458051B19de652F6',
  commissionRate: 2000
}

const baseUrl = 'https://widget.xy.finance?'
const searchParams = queryString.stringify(config)
const iframeSrc = ref(baseUrl + searchParams)
</script>

<template>
  <div class="container">
    <iframe :width="480" :height="700" :src="iframeSrc" />
  </div>
</template>

<style scoped>
.container {
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}
</style>

// widget-iframe/v1/nextjs/app/page.tsx
import queryString from 'query-string'

export default function Home() {
  const config = {
    fromTokenAddress: '0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE',
    sourceChainId: '1',
    toTokenAddress: '0x77777777772cf0455fB38eE0e75f38034dFa50DE',
    targetChainId: '1',
    amount: 1,
    slippage: '1',
    orientation: 'portrait',
    theme: 'dark',
    lockmode: 'none',
    pagecolor: null,
    referrer: null
  }
  const url = queryString.stringify(config)
  // amount=1&fromTokenAddress=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&lockmode=none&orientation=portrait&pagecolor&referrer&slippage=1&sourceChainId=1&targetChainId=1&theme=dark&toTokenAddress=0x77777777772cf0455fB38eE0e75f38034dFa50DE

  const src = `https://widget.xy.finance/?${url}`
  // "You can change the iframe size. Recommended settings: width 480, height 700."
  const width = 480
  const height = 700

  return (
    <div>
      <iframe width={width} height={height} src={src} />
    </div>
  )
}
